### ISSUE TITLE
Why Get Citation Data Error? 

### ISSUE THREAD

**Issue by xinchen-jzx** [RayeRen/acad-homepage.github.io#48]
]
![屏幕截图 2023-11-13 202354](https://github.com/RayeRen/acad-homepage.github.io/assets/116535195/d40b559a-0e26-43da-b7f4-edc65abc9192)

**Comment by Jacoo-Zhao** [comment]
Same. I tried to update the Main branch and it works, workfolw results runing smoothly. However, my problem is the wrong number of citations. Looking for answer.

**Comment by qm19** [comment]
I had the same problem. When building, workflow gets the error "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.”

**Comment by Jun-jie-Huang** [comment]
I met the same problem. Does anyone know how to solve it?

**Comment by Ruijun19** [comment]
Same question. In Run, my error is:

 "Traceback (most recent call last):
  File "/home/runner/work/Ruijun19.github.io/Ruijun19.github.io/google_scholar_crawler/main.py", line 7, in <module>
    author: dict = scholarly.search_author_id(os.environ['GOOGLE_SCHOLAR_ID'])
  File "/home/runner/.local/lib/python3.10/site-packages/scholarly/_scholarly.py", line 283, in search_author_id
    return self.__nav.search_author_id(id, filled, sortby, publication_limit)
  File "/home/runner/.local/lib/python3.10/site-packages/scholarly/_navigator.py", line 298, in search_author_id
    res = author_parser.fill(res, sections=['basics'], sortby=sortby, publication_limit=publication_limit)
  File "/home/runner/.local/lib/python3.10/site-packages/scholarly/author_parser.py", line 444, in fill
    raise(e)
  File "/home/runner/.local/lib/python3.10/site-packages/scholarly/author_parser.py", line 441, in fill
    (getattr(self, f'_fill_{i}')(soup, author) if i != 'publications' else getattr(self, f'_fill_{i}')(soup, author, publication_limit, sortby_str))
  File "/home/runner/.local/lib/python3.10/site-packages/scholarly/author_parser.py", line 77, in _fill_basics
    author['name'] = soup.find('div', id='gsc_prf_in').text
AttributeError: 'NoneType' object has no attribute 'text'
Error: Process completed with exit code 1."
